### ISSUE TITLE
Decrease the gap between the checkboxes

### ISSUE THREAD

**Issue by Rangertheman** [Rangertheman/fwrpg-for-pbta#20]
I can't find the CSS element that needs to change to bring the checkboxes closer toghether. Thank you in advance!
![Growth](https://github.com/Rangertheman/fwrpg-for-pbta/assets/81484515/10e9b2bf-0e5c-4c0b-a6ba-d6af9f3af851)

**Comment by mclemente** [comment]
Change the 5px to a smaller value.
```css
.pbta.sheet .cell--attributes-left .cell__checkboxes input[type="checkbox"]:has(+ input),
.pbta.sheet .cell--attributes-left .cell__checkboxes input[type="checkbox"] + input {
  margin: 3px 5px;
}
```

This won't affect single checkboxes, these can be targetted with `.pbta.sheet .cell--attributes-left .cell__checkboxes input[type="checkbox"]`
